// <auto-generated />
using System;
using Absa.Infrastructure.EntityFramework.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Absa.Infrastructure.EntityFramework.Data.Migrations.AppMigrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Absa.Infrastructure.EntityFramework.Entities.Entry", b =>
                {
                    b.Property<Guid>("EntryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("PhonebookId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("EntryId");

                    b.HasIndex("PhonebookId");

                    b.ToTable("Entries", "Absa");
                });

            modelBuilder.Entity("Absa.Infrastructure.EntityFramework.Entities.Phonebook", b =>
                {
                    b.Property<Guid>("PhonebookId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhonebookId");

                    b.ToTable("Phonebooks", "Absa");
                });

            modelBuilder.Entity("Absa.Infrastructure.EntityFramework.Entities.Entry", b =>
                {
                    b.HasOne("Absa.Infrastructure.EntityFramework.Entities.Phonebook", "Phonebook")
                        .WithMany()
                        .HasForeignKey("PhonebookId");

                    b.Navigation("Phonebook");
                });
#pragma warning restore 612, 618
        }
    }
}
